name: CI/CD

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Configure WASM tooling
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk wasm-bindgen-cli

      - name: Install Node dependencies
        run: |
          npm ci

      - name: Quality - Code Formatting
        run: cargo fmt --check

      - name: Quality - Unit Tests
        run: cargo test

      - name: Build Application
        run: |
          trunk build --release
          cp ./staticwebapp.config.json ./dist

      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_DEPLOYMENT_APP_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_DEPLOYMENT_APP_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_DEPLOYMENT_APP_SUBSCRIPTION_ID }}

      - name: Debug
        run: |
          az account show