name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Configure WASM tooling
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk wasm-bindgen-cli

      - name: Install Node dependencies
        run: |
          npm install -g @azure/static-web-apps-cli
          npm ci

      - name: Quality - Code Formatting
        run: cargo fmt --check

      - name: Quality - Unit Tests
        run: cargo test

      - name: Build Application
        run: |
          trunk build --release
          # cp ./staticwebapp.config.json ./dist

      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_DEPLOYMENT_APP_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_DEPLOYMENT_APP_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_DEPLOYMENT_APP_SUBSCRIPTION_ID }}

      - name: Deploy Azure Deployment Stack
        id: deploystack
        uses: azure/bicep-deploy@v2
        with:
          type: deploymentStack
          operation: create
          name: stack-countdown-solver
          description: Countdown Solver Deployment Stack
          location: westeurope
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_DEPLOYMENT_APP_SUBSCRIPTION_ID }}
          resource-group-name: rg-countdown-solver
          template-file: ./deploy/main.bicep
          action-on-unmanage-resources: delete
          deny-settings-mode: denyWriteAndDelete

      - name: Deploy to Azure Static Web App
        run: |
          deploymentToken=$(az staticwebapp secrets list --name ${{ steps.deploystack.outputs.staticWebAppName }} --query "properties.apiKey" -o tsv)
          swa deploy ./dist --token $deploymentToken